//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDaysInBulgaria.ConsoleClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBulgarianDayService")]
    public interface IBulgarianDayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBulgarianDayService/GetDayName", ReplyAction="http://tempuri.org/IBulgarianDayService/GetDayNameResponse")]
        string GetDayName(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBulgarianDayService/GetDayName", ReplyAction="http://tempuri.org/IBulgarianDayService/GetDayNameResponse")]
        System.Threading.Tasks.Task<string> GetDayNameAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBulgarianDayServiceChannel : TheDaysInBulgaria.ConsoleClient.ServiceReference.IBulgarianDayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BulgarianDayServiceClient : System.ServiceModel.ClientBase<TheDaysInBulgaria.ConsoleClient.ServiceReference.IBulgarianDayService>, TheDaysInBulgaria.ConsoleClient.ServiceReference.IBulgarianDayService {
        
        public BulgarianDayServiceClient() {
        }
        
        public BulgarianDayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BulgarianDayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulgarianDayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulgarianDayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayName(System.DateTime date) {
            return base.Channel.GetDayName(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayNameAsync(System.DateTime date) {
            return base.Channel.GetDayNameAsync(date);
        }
    }
}
